log4j.rootLogger=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c{1} - %m%n

log4j.logger.org.apache.flink=INFO
log4j.logger.org.apache.flink.connector.kafka=INFO
log4j.logger.org.apache.kafka.clients.consumer=INFO
log4j.logger.io.delta=INFO
log4j.logger.org.apache.hadoop=WARN
